POST http://127.0.0.1:6570/auth/register
Content-Type: application/json

{
    "username": "devuser",
    "password": "devpassword"
}

# birthday <-- new Date(2000, 10, 21).toISOString()

###

POST http://127.0.0.1:6570/auth/login
Content-Type: application/json

{
    "username": "devuser",
    "password": "devpassword"
}

###

POST http://127.0.0.1:6570/auth/logout
Authorization: Bearer testtoken
