POST http://127.0.0.1:6570/auth/register
Content-Type: application/json

{
    "username": "adrii",
    "email": "adrii@secret.mp4",
    "password": "somepassword"
}

###

POST http://127.0.0.1:6570/auth/login
Content-Type: application/json

{
    "email": "adrii@secret.mp4",
    "password": "somepassword"
}

###

POST http://127.0.0.1:6570/auth/logout
Content-Type: application/json
Authorization: helloworld

{"hello": "world"}