GET http://127.0.0.1:6570/friends
Authorization: Bearer testtoken

###

GET http://127.0.0.1:6570/friends/has/user_id
Authorization: Bearer testtoken

###

POST http://127.0.0.1:6570/friends/add/user_id
Authorization: Bearer testtoken

###

POST http://127.0.0.1:6570/friends/remove/user_id
Authorization: Bearer testtoken
