GET http://127.0.0.1:6570/profile
Authorization: Bearer testtoken

###

GET http://127.0.0.1:6570/profile/user_id

###

POST http://127.0.0.1:6570/profile/create
Content-Type: application/json
Authorization: Bearer testtoken

{"display_name": "devuser", "birthday": "1990-05-01 00:00:00"}

###

POST http://127.0.0.1:6570/profile/update
Content-Type: application/json
Authorization: Bearer testtoken

{"display_name": "dev user new name"}
