GET http://127.0.0.1:6570/profile/1
Authorization: Bearer testtoken

###

GET http://127.0.0.1:6570/profile/1

###

POST http://127.0.0.1:6570/profile/create
Content-Type: application/json
Authorization: Bearer testtoken

{"username": "devuser", "birthday": "1990-05-01 00:00:00"}

###

# http://127.0.0.1:6570/profile/update/option --> body = {"option": "value"}, example using username:
POST http://127.0.0.1:6570/profile/update/username
Content-Type: application/json
Authorization: Bearer testtoken

{"username": "dev user new name"}
